// Generate the Tailwind v4 @theme + raw CSS-var layer from the vendored
// fw-example design tokens. Single source of truth: tokens/*.json.
//
//   node scripts/gen-theme.mjs
//
// Emits:
//   src/tokens.css  — full :root variable layer (every primitive + semantic var)
//   src/theme.css   — @import "./tokens.css" + a curated shadcn-style @theme that
//                     maps our semantic tokens to Tailwind color/radius/font names.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = join(here, '..', 'tokens');
const outDir = join(here, '..', 'src');

const load = (f) => JSON.parse(readFileSync(join(tokensDir, f), 'utf8'));

/** Walk a W3C token tree → flat [{ varName, value }]. */
function walk(obj, path = []) {
  const out = [];
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('$')) continue;
    if (v && v.$value !== undefined) out.push({ path: [...path, k], value: v.$value });
    else if (v && typeof v === 'object') out.push(...walk(v, [...path, k]));
  }
  return out;
}
const varName = (path) => '--' + path.join('-');
const fmtFont = (v) => (Array.isArray(v) ? v : [v])
  .map((f) => (/\s/.test(f) && !f.includes(',') ? `"${f}"` : f)).join(', ');

// --- raw :root layer (tokens.css) -----------------------------------------
const files = readdirSync(tokensDir).filter((f) => f.endsWith('.json')).sort();
const rootLines = [];
for (const f of files) {
  const leaves = walk(load(f));
  rootLines.push(`  /* ${basename(f, '.json')}.json */`);
  for (const { path, value } of leaves) {
    const v = Array.isArray(value) ? fmtFont(value) : String(value);
    rootLines.push(`  ${varName(path)}: ${v};`);
  }
  rootLines.push('');
}
const tokensCss =
  `/* GENERATED by scripts/gen-theme.mjs — do not edit. Source: tokens/*.json */\n` +
  `:root {\n  color-scheme: light dark;\n${rootLines.join('\n')}}\n`;
writeFileSync(join(outDir, 'tokens.css'), tokensCss);

// --- curated @theme (theme.css) --------------------------------------------
// Map a Tailwind color name → a semantic token "group.key" (from semantic.json).
// These become utilities: bg-primary, text-muted-foreground, border-border, …
// Values are emitted as var(--<group>-<key>) refs into the raw layer above, so
// light-dark() auto-switching is preserved with zero duplication.
const semanticColor = {
  background: 'bg-primary',          foreground: 'text-primary',
  card: 'bg-primary',                'card-foreground': 'text-primary',
  popover: 'bg-primary',             'popover-foreground': 'text-primary',
  muted: 'bg-secondary',             'muted-foreground': 'text-secondary',
  accent: 'bg-tertiary',             'accent-foreground': 'text-primary',
  primary: 'bg-brand',               'primary-hover': 'bg-brand-hover',
  'primary-foreground': 'text-on-brand',
  secondary: 'bg-secondary',         'secondary-hover': 'bg-secondary-hover',
  'secondary-foreground': 'text-primary',
  destructive: 'bg-critical',        'destructive-hover': 'bg-critical-hover',
  'destructive-foreground': 'text-on-brand',
  success: 'bg-success',             'success-foreground': 'text-on-brand',
  alert: 'bg-alert',                 'alert-foreground': 'text-primary',
  'brand-subtle': 'bg-brand-secondary',
  'critical-subtle': 'bg-critical-secondary',
  'success-subtle': 'bg-success-secondary',
  'alert-subtle': 'bg-alert-secondary',
  'text-brand': 'text-brand',        'text-critical': 'text-critical',
  'text-success': 'text-success',
  border: 'border-tertiary',         'border-strong': 'border-primary',
  input: 'input-border',             'input-hover': 'input-border-hover',
  ring: 'border-active',             overlay: 'bg-transparent-strongest',
};

const themeLines = [];
themeLines.push('  /* fonts */');
themeLines.push('  --font-sans: var(--font-family-body);');
themeLines.push('  --font-mono: var(--font-family-mono);');
themeLines.push('');
themeLines.push('  /* radius */');
themeLines.push('  --radius-control: var(--button-radius);');
themeLines.push('  --radius-panel: var(--panel-radius);');
themeLines.push('  --radius-full: var(--radius-full);');
themeLines.push('');
themeLines.push('  /* colors (semantic, light-dark auto-switching) */');
for (const [name, token] of Object.entries(semanticColor)) {
  themeLines.push(`  --color-${name}: var(--${token});`);
}

const themeCss =
  `/* GENERATED by scripts/gen-theme.mjs — do not edit. Source: tokens/*.json */\n` +
  `@import "./tokens.css";\n\n@theme inline {\n${themeLines.join('\n')}\n}\n`;
writeFileSync(join(outDir, 'theme.css'), themeCss);

console.log('✓ wrote src/tokens.css and src/theme.css');
